---
title: "Diamond_Project_2"
author: "Ali Valiyev"
date: "2024-03-19"
output:
  pdf_document: default
  html_document: default
---``

```{r}
#Ilk Once "tidyverse" ve "dplyr" paketlerimizi kuruyoruz 
clone_diamonds = ggplot2::diamonds
library(tidyverse)
library(dplyr)
```

```{r}
#Verisetinden Bizim kullanabilecegimiz  kismi filter fonksiyonu ile filtreliyoruz.
sub_diamonds = filter(clone_diamonds, price<=5000)
sub_diamonds
```


```{r}
#Biz en iyi 2 kesimin her birinin en uygun optimum pirlantasını bularak 5000 doları en iyi şekilde değerlendirmeye çalışacağız. İlk olarak "Ideal" kesimden başlayacağız. filter fonksiyonu sayesinde alt-verisetinden Ideal kesime sahip pırlantaları seçiyoruz
sub_diamonds = filter(sub_diamonds, cut=="Ideal")
sub_diamonds
```

```{r}
#Geom_point fonksiyonunu kullanarak karat ve fiyat arasındaki dağılımın görsel halini görebiliyoruz. Bu görsel dagılımda en uygun karatın 1 seviyelerinde olduğu anlaşılıyor. Fiyat Performans ürünü olarak 2500 dolar civarı olan ve karatı 0.8-den yüksek olan ürünler Ideal kesim pırlantalar arasında en iyi seçime benziyor.
Best_diamonds = ggplot(data=sub_diamonds) +
  geom_point(mapping = aes(x = carat, y = price))
Best_diamonds
```
```{r}
#2500 dolardan az ve karatı birden az olan pırlantaları sıralayalım.
sub_diamonds = filter(sub_diamonds, price<2500 & carat<=1)
sub_diamonds
```
```{r}
#Ürünler arasında clarity açısından en kötü diyebileceğimiz pırlantaları eliyoruz.
sub_diamonds = filter(sub_diamonds, carat>0.8 & clarity!="I1")
sub_diamonds
```
```{r}
#Elimizdeki son 26 ürün içersinde karat ve fiyatının renk açısından nasıl değerlendirebileceğimizi anlamak icin geom_boxplot fonksiyonu facet_wrap fonksiyonuyla birlikte kullanalım 
Best_diamonds = ggplot(data=sub_diamonds) +
  geom_boxplot(mapping = aes(x = carat, y = price)) +
  facet_wrap(~color)
Best_diamonds
```
Görselden de anlayacağımız üzere Fiyat-Performans olarak F - rengine sahip pırlanta en uygun seçim olacaktır

```{r}
#F rengine sahip pirlantayi secelim.
sub_diamonds = filter(sub_diamonds, color=="F")
sub_diamonds
```


```{r}
#Paramızın kalan kısmıyla alabileceğimiz pırlantaları filtreliyelim.
clone_diamonds = ggplot2::diamonds
sub_diamonds = filter(clone_diamonds, price<=2614)
sub_diamonds
```

```{r}
#Pirlantalar içinde "Premium" kesime sahip olan pırlantaları ayıralım
sub_diamonds = filter(sub_diamonds, cut=="Premium")
sub_diamonds
```


```{r}
#Geom_point fonksiyonunu kullanarak karat ve fiyat arasındakı dağılımın clarity-e nazaran gğrsel halını görebiliyoruz. Bu görsel dağılımda en uygun karatın 0.75 seviyelerinde olduğu anlaşılıyor. Fiyat Performans ürünü olarak 2000 dolar üzeri olan ve renki ve clarity-si en kötü halinden farklı olan ürünler Premium kesim pırlantalar arasında en iyi seçime benziyor.
Best_diamonds = ggplot(data=sub_diamonds) +
  geom_point(mapping = aes(x = carat, y = price,color=clarity))
Best_diamonds
```
```{r}
#2000 dolardan çok ve karatı 0.8-den çok olan pırlantaları sıralayalım.
sub_diamonds = filter(sub_diamonds, price>2000& carat>0.75)
sub_diamonds
```
```{r}
#Ürünler arasında clarity ve color açısından en kötü diyebileceğimiz pırlantaları eliyoruz.
sub_diamonds = filter(sub_diamonds, color != "J" & clarity != "I1")
sub_diamonds
```

```{r}
#Elimizdeki son 95 ürün içersinde clarity ve fiyatının renk açısından nasıl değerlendirebileceğimizi anlamak için geom_boxplot fonksiyonunu facet_wrap fonksiyonuyla birlikte kullanalım 
Best_diamonds = ggplot(data=sub_diamonds) +
  geom_boxplot(mapping = aes(x = clarity, y = price)) +
  facet_wrap(~color)
Best_diamonds
```
Goruldugu uzere "F" rengine sahip "SI1" Clarity tipli pirlanta Fiyat-performans olarak "Premium" kesim olan en iyi pirlanta diyebiliriz

```{r}
#aradığımız pırlantayı seçelim
sub_diamonds = filter(sub_diamonds, color == "F" & clarity == "SI1")
sub_diamonds
```
bu 4 Pirlanta icinde 0.81 karatlik pirlanta satinalabilecegimiz en iyi pirlanta diyebiliriz
